#
###################################
# Site wide configuration
####################################
#
title: Léo Hackin @ 2023
author: Léo Hackin
email:
description: Dev, Geek e Incorrigível Otimista que gosta de criar coisas e resolver problemas (quase sempre) com tecnologia.
url: //leohackin.com.br # the base hostname & protocol for your site
keywords:
  [
    "blog",
    "leohackin",
    "software engineer",
    "engineering",
    "development",
    "gtd",
    "ztd",
    "pomodoros",
    "ecommerce",
    "shopify"
  ]

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-feed

feed:
  path: atom.xml
  excerpt_only: true

languages: ["pt-br", "en"]
exclude_from_localizations: ["javascript", "images", "css"]

#
###################################
# Jekyll configuration
####################################
#
timezone: Brazil/SaoPaulo
markdown: kramdown
highlighter: red
excerpt_separator: <!--more-->
permalink: /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Léo Hackin
  avatar: hackin.png
  # job: "No flow de aprendizado contínuo"
  bio: "Dev, Geek e Incorrigível Otimista que gosta de criar coisas e resolver problemas (quase sempre) com tecnologia."
  email:
  disqus-shortname: leohackin
  twitter: leohackin
  facebook: #leohackin
  google:
    plus: #username
    analytics: UA-1254429-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: leohackin
  gitlab: leohackin
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: leohackin
  skype: #username
  xing: #username
  instagram: leohackin
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
